In [19]:
import pandas as pd

In [20]:
df = pd.read_csv('/home/maiconkevyn/PycharmProjects/txt2sql_claude/data/CID-10-CAPITULOS.csv', sep=';')
df.head(20)

,NUMCAP,CATINIC,CATFIM,DESCRICAO,DESCRABREV,Unnamed: 5
0,1,A00,B99,Capitulo I - Algumas Doenças infecciosas e par...,I. Algumas Doenças infecciosas e parasitárias,NaN
1,2,C00,D48,Capitulo II - Neoplasias [tumores],II. Neoplasias (tumores),NaN
2,3,D50,D89,Capitulo III - Doenças do sangue e dos órgãos...,III. Doenças sangue órgãos hemat e transt imun...,NaN
3,4,E00,E90,"Capitulo IV - Doenças endócrinas, nutricionais...",IV. Doenças endócrinas nutricionais e metaból...,NaN
4,5,F00,F99,Capitulo V - Transtornos mentais e comportamen...,V. Transtornos mentais e comportamentais,NaN
5,6,G00,G99,Capitulo VI - Doenças do sistema nervoso,VI. Doenças do sistema nervoso,NaN
6,7,H00,H59,Capitulo VII - Doenças do olho e anexos,VII. Doenças do olho e anexos,NaN
7,8,H60,H95,Capitulo VIII - Doenças do ouvido e da apófise...,VIII.Doenças do ouvido e da apófise mastóide,NaN
8,9,I00,I99,Capitulo IX - Doenças do aparelho circulatório,IX. Doenças do aparelho circulatório,NaN
9,10,J00,J99,Capitulo X - Doenças do aparelho respiratório,X. Doenças do aparelho respiratório,NaN
10,11,K00,K93,Capitulo XI - Doenças do aparelho digestivo,XI. Doenças do aparelho digestivo,NaN
11,12,L00,L99,Capitulo XII - Doenças da pele e do tecido sub...,XII. Doenças da pele e do tecido subcutâneo,NaN
12,13,M00,M99,Capitulo XIII - Doenças do sistema osteomuscul...,XIII.Doenças sist osteomuscular e tec conjuntivo,NaN
13,14,N00,N99,Capitulo XIV - Doenças do aparelho geniturinário,XIV. Doenças do aparelho geniturinário,NaN
14,15,O00,O99,"Capitulo XV - Gravidez, parto e puerpério",XV. Gravidez parto e puerpério,NaN
15,16,P00,P96,Capitulo XVI - Algumas afecções originadas no ...,XVI. Algumas afec originadas no período perinatal,NaN
16,17,Q00,Q99,"Capitulo XVII - Malformações congênitas, defor...",XVII.Malf cong deformid e anomalias cromossômicas,NaN
17,18,R00,R99,"Capitulo XVIII - Sintomas, sinais e achados an...",XVIII.Sint sinais e achad anorm ex clín e laborat,NaN
18,19,S00,T98,"Capitulo XIX - Lesões, envenenamento e algumas...",XIX. Lesões enven e alg out conseq causas exte...,NaN
19,20,V01,Y98,Capitulo XX - Causas externas de morbidade e d...,XX. Causas externas de morbidade e mortalidade,NaN

In [21]:
df['CID_GERAL'] = df['CATINIC'].str[0]
df.head(20)

,NUMCAP,CATINIC,CATFIM,DESCRICAO,DESCRABREV,Unnamed: 5,CID_GERAL
0,1,A00,B99,Capitulo I - Algumas Doenças infecciosas e par...,I. Algumas Doenças infecciosas e parasitárias,NaN,A
1,2,C00,D48,Capitulo II - Neoplasias [tumores],II. Neoplasias (tumores),NaN,C
2,3,D50,D89,Capitulo III - Doenças do sangue e dos órgãos...,III. Doenças sangue órgãos hemat e transt imun...,NaN,D
3,4,E00,E90,"Capitulo IV - Doenças endócrinas, nutricionais...",IV. Doenças endócrinas nutricionais e metaból...,NaN,E
4,5,F00,F99,Capitulo V - Transtornos mentais e comportamen...,V. Transtornos mentais e comportamentais,NaN,F
5,6,G00,G99,Capitulo VI - Doenças do sistema nervoso,VI. Doenças do sistema nervoso,NaN,G
6,7,H00,H59,Capitulo VII - Doenças do olho e anexos,VII. Doenças do olho e anexos,NaN,H
7,8,H60,H95,Capitulo VIII - Doenças do ouvido e da apófise...,VIII.Doenças do ouvido e da apófise mastóide,NaN,H
8,9,I00,I99,Capitulo IX - Doenças do aparelho circulatório,IX. Doenças do aparelho circulatório,NaN,I
9,10,J00,J99,Capitulo X - Doenças do aparelho respiratório,X. Doenças do aparelho respiratório,NaN,J
10,11,K00,K93,Capitulo XI - Doenças do aparelho digestivo,XI. Doenças do aparelho digestivo,NaN,K
11,12,L00,L99,Capitulo XII - Doenças da pele e do tecido sub...,XII. Doenças da pele e do tecido subcutâneo,NaN,L
12,13,M00,M99,Capitulo XIII - Doenças do sistema osteomuscul...,XIII.Doenças sist osteomuscular e tec conjuntivo,NaN,M
13,14,N00,N99,Capitulo XIV - Doenças do aparelho geniturinário,XIV. Doenças do aparelho geniturinário,NaN,N
14,15,O00,O99,"Capitulo XV - Gravidez, parto e puerpério",XV. Gravidez parto e puerpério,NaN,O
15,16,P00,P96,Capitulo XVI - Algumas afecções originadas no ...,XVI. Algumas afec originadas no período perinatal,NaN,P
16,17,Q00,Q99,"Capitulo XVII - Malformações congênitas, defor...",XVII.Malf cong deformid e anomalias cromossômicas,NaN,Q
17,18,R00,R99,"Capitulo XVIII - Sintomas, sinais e achados an...",XVIII.Sint sinais e achad anorm ex clín e laborat,NaN,R
18,19,S00,T98,"Capitulo XIX - Lesões, envenenamento e algumas...",XIX. Lesões enven e alg out conseq causas exte...,NaN,S
19,20,V01,Y98,Capitulo XX - Causas externas de morbidade e d...,XX. Causas externas de morbidade e mortalidade,NaN,V

In [22]:
df.drop(columns=['Unnamed: 5'], inplace=True)

In [23]:
dados_sus = pd.read_csv('/home/maiconkevyn/PycharmProjects/txt2sql_claude/data/dados_sus3.csv', sep=',')

dados_sus.head()

,DIAG_PRINC,MUNIC_RES,MUNIC_MOV,PROC_REA,IDADE,SEXO,CID_MORTE,MORTE,CNES,VAL_TOT,UTI_MES_TO,DT_INTER,DT_SAIDA,total_ocorrencias,UF_RESIDENCIA_PACIENTE,CIDADE_RESIDENCIA_PACIENTE,LATI_CIDADE_RES,LONG_CIDADE_RES
0,A46,430300,430300,303080078,67,3,0,0,2266474,292.62,0,20170803,20170808,24485,Rio Grande do Sul,Santa Maria,-29.686051,-53.806921
1,C168,430300,430300,304100021,60,1,0,0,2266474,797.11,0,20170803,20170805,24485,Rio Grande do Sul,Santa Maria,-29.686051,-53.806921
2,J128,430300,430300,303140151,76,3,0,1,2266474,4987.52,8,20170726,20170803,24485,Rio Grande do Sul,Santa Maria,-29.686051,-53.806921
3,I500,430300,430300,303060212,62,1,0,1,2266474,2702.50,4,20170802,20170805,24485,Rio Grande do Sul,Santa Maria,-29.686051,-53.806921
4,I158,430300,430300,303060107,29,3,0,0,2266474,1737.69,2,20170804,20170810,24485,Rio Grande do Sul,Santa Maria,-29.686051,-53.806921

In [24]:
casos_j = dados_sus[dados_sus['DIAG_PRINC'].str.startswith('J')]
casos_j.shape

(2785, 18)

In [25]:
casos_j.SEXO.value_counts()

SEXO
1    1565
3    1220
Name: count, dtype: int64

In [26]:
casos_j

,DIAG_PRINC,MUNIC_RES,MUNIC_MOV,PROC_REA,IDADE,SEXO,CID_MORTE,MORTE,CNES,VAL_TOT,UTI_MES_TO,DT_INTER,DT_SAIDA,total_ocorrencias,UF_RESIDENCIA_PACIENTE,CIDADE_RESIDENCIA_PACIENTE,LATI_CIDADE_RES,LONG_CIDADE_RES
2,J128,430300,430300,303140151,76,3,0,1,2266474,4987.52,8,20170726,20170803,24485,Rio Grande do Sul,Santa Maria,-29.686051,-53.806921
6,J068,430300,430300,303140100,4,1,0,0,2266474,193.07,0,20170801,20170803,24485,Rio Grande do Sul,Santa Maria,-29.686051,-53.806921
8,J459,430300,430300,303140046,2,1,0,0,2266474,529.87,0,20170803,20170807,24485,Rio Grande do Sul,Santa Maria,-29.686051,-53.806921
34,J984,430300,430300,412030012,55,1,0,0,2266474,2273.43,0,20170810,20170813,24485,Rio Grande do Sul,Santa Maria,-29.686051,-53.806921
50,J210,430300,430300,303140143,4,3,0,0,2266474,211.13,0,20170726,20170729,24485,Rio Grande do Sul,Santa Maria,-29.686051,-53.806921
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58539,J984,430410,431410,412030012,75,1,0000,0,2246988,2382.74,0,20150818,20150825,915,Rio Grande do Sul,Uruguaiana,-29.756073,-57.086755
58606,J852,430545,432160,303140038,20,1,0000,0,2793008,5726.31,10,20150906,20150924,4290,Rio Grande do Sul,Ijuí,-28.387873,-53.920169
58608,J343,430463,430463,404010415,67,1,0000,0,2707969,323.65,0,20151019,20151020,15291,Rio Grande do Sul,Uruguaiana,-29.756073,-57.086755
58634,J342,430210,430210,404010520,65,1,0000,0,2241021,213.75,0,20151021,20151022,25561,Rio Grande do Sul,Pelotas,-31.769974,-52.341016
58648,J432,430460,430460,412050137,43,1,,0,3508528,1919.90,1,20140312,20140317,116612,Rio Grande do Sul,Uruguaiana,-29.756073,-57.086755

In [27]:
casos_j.columns

Index(['DIAG_PRINC', 'MUNIC_RES', 'MUNIC_MOV', 'PROC_REA', 'IDADE', 'SEXO',
       'CID_MORTE', 'MORTE', 'CNES', 'VAL_TOT', 'UTI_MES_TO', 'DT_INTER',
       'DT_SAIDA', 'total_ocorrencias', 'UF_RESIDENCIA_PACIENTE',
       'CIDADE_RESIDENCIA_PACIENTE', 'LATI_CIDADE_RES', 'LONG_CIDADE_RES'],
      dtype='object')

In [9]:
df2 = pd.read_csv('/home/maiconkevyn/PycharmProjects/txt2sql_claude/data/dados_sus3.csv')

In [10]:
df2[(df2.SEXO==1) & (df2.MORTE==1)].CIDADE_RESIDENCIA_PACIENTE.value_counts()

CIDADE_RESIDENCIA_PACIENTE
Ijuí                           212
Uruguaiana                     186
Passo Fundo                    184
Porto Alegre                   170
Pelotas                        143
Caxias do Sul                  127
Santa Maria                    112
Santa Cruz do Sul - Lajeado    102
Name: count, dtype: int64

In [29]:
casos_jan_abr_2017 = casos_j[(casos_j['DT_INTER'].astype(str) >= '20170101') &
                             (casos_j['DT_INTER'].astype(str) <= '20170431')]
# Contando o número total de casos nesse período
total_casos = len(casos_jan_abr_2017)
print(f"Total de casos entre janeiro e abril de 2017: {total_casos}")

Total de casos entre janeiro e abril de 2017: 51

In [ ]:
casos_jan_abr_2017 = df2[(df2['DT_INTER'].astype(str) >= '20170101') &
                             (df2['DT_INTER'].astype(str) <= '20170531')]

# Contando o número total de casos nesse período
total_casos = len(casos_jan_abr_2017)
print(f"Total de casos entre janeiro e abril de 2017: {total_casos}")

In [15]:
# Calculando o tempo médio de internação usando DT_SAIDA e DT_INTER
# Primeiro, convertemos as colunas para datetime
import pandas as pd
from datetime import datetime

# Convertendo colunas para datetime
casos_j['DT_INTER_DATE'] = pd.to_datetime(casos_j['DT_INTER'].astype(str), format='%Y%m%d', errors='coerce')
casos_j['DT_SAIDA_DATE'] = pd.to_datetime(casos_j['DT_SAIDA'].astype(str), format='%Y%m%d', errors='coerce')

# Calculando a diferença em dias
casos_j['TEMPO_INTERNACAO'] = (casos_j['DT_SAIDA_DATE'] - casos_j['DT_INTER_DATE']).dt.days

# Filtrando apenas registros com tempo de internação válido (positivo)
casos_validos = casos_j[casos_j['TEMPO_INTERNACAO'] >= 0].copy()

# Calculando estatísticas do tempo de internação
tempo_medio = casos_validos['TEMPO_INTERNACAO'].mean()

print(f"Tempo médio de internação: {tempo_medio:.2f} dias")
print(f"Tempo mediano de internação: {tempo_mediano:.2f} dias")
print(f"Tempo mínimo de internação: {tempo_minimo:.0f} dias")
print(f"Tempo máximo de internação: {tempo_maximo:.0f} dias")

Tempo médio de internação: 6.09 dias
Tempo mediano de internação: 3.00 dias
Tempo mínimo de internação: 0 dias
Tempo máximo de internação: 95 dias

/tmp/ipykernel_114918/74922935.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  casos_j['DT_INTER_DATE'] = pd.to_datetime(casos_j['DT_INTER'].astype(str), format='%Y%m%d', errors='coerce')
/tmp/ipykernel_114918/74922935.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  casos_j['DT_SAIDA_DATE'] = pd.to_datetime(casos_j['DT_SAIDA'].astype(str), format='%Y%m%d', errors='coerce')
/tmp/ipykernel_114918/74922935.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  casos_j['TEMPO_INTERNACAO'] = (casos_j['DT_SAIDA_DATE'] - casos_j['DT_INTER_DATE']).dt.days