In [18]:
import pandas as pd

In [19]:
df = pd.read_csv('/home/maiconkevyn/PycharmProjects/txt2sql_claude/data/CID-10-CAPITULOS.csv', sep=';')
df.head(20)

,NUMCAP,CATINIC,CATFIM,DESCRICAO,DESCRABREV,Unnamed: 5
0,1,A00,B99,Capitulo I - Algumas Doenças infecciosas e par...,I. Algumas Doenças infecciosas e parasitárias,NaN
1,2,C00,D48,Capitulo II - Neoplasias [tumores],II. Neoplasias (tumores),NaN
2,3,D50,D89,Capitulo III - Doenças do sangue e dos órgãos...,III. Doenças sangue órgãos hemat e transt imun...,NaN
3,4,E00,E90,"Capitulo IV - Doenças endócrinas, nutricionais...",IV. Doenças endócrinas nutricionais e metaból...,NaN
4,5,F00,F99,Capitulo V - Transtornos mentais e comportamen...,V. Transtornos mentais e comportamentais,NaN
5,6,G00,G99,Capitulo VI - Doenças do sistema nervoso,VI. Doenças do sistema nervoso,NaN
6,7,H00,H59,Capitulo VII - Doenças do olho e anexos,VII. Doenças do olho e anexos,NaN
7,8,H60,H95,Capitulo VIII - Doenças do ouvido e da apófise...,VIII.Doenças do ouvido e da apófise mastóide,NaN
8,9,I00,I99,Capitulo IX - Doenças do aparelho circulatório,IX. Doenças do aparelho circulatório,NaN
9,10,J00,J99,Capitulo X - Doenças do aparelho respiratório,X. Doenças do aparelho respiratório,NaN
10,11,K00,K93,Capitulo XI - Doenças do aparelho digestivo,XI. Doenças do aparelho digestivo,NaN
11,12,L00,L99,Capitulo XII - Doenças da pele e do tecido sub...,XII. Doenças da pele e do tecido subcutâneo,NaN
12,13,M00,M99,Capitulo XIII - Doenças do sistema osteomuscul...,XIII.Doenças sist osteomuscular e tec conjuntivo,NaN
13,14,N00,N99,Capitulo XIV - Doenças do aparelho geniturinário,XIV. Doenças do aparelho geniturinário,NaN
14,15,O00,O99,"Capitulo XV - Gravidez, parto e puerpério",XV. Gravidez parto e puerpério,NaN
15,16,P00,P96,Capitulo XVI - Algumas afecções originadas no ...,XVI. Algumas afec originadas no período perinatal,NaN
16,17,Q00,Q99,"Capitulo XVII - Malformações congênitas, defor...",XVII.Malf cong deformid e anomalias cromossômicas,NaN
17,18,R00,R99,"Capitulo XVIII - Sintomas, sinais e achados an...",XVIII.Sint sinais e achad anorm ex clín e laborat,NaN
18,19,S00,T98,"Capitulo XIX - Lesões, envenenamento e algumas...",XIX. Lesões enven e alg out conseq causas exte...,NaN
19,20,V01,Y98,Capitulo XX - Causas externas de morbidade e d...,XX. Causas externas de morbidade e mortalidade,NaN

In [20]:
df['CID_GERAL'] = df['CATINIC'].str[0]
df.head(20)

,NUMCAP,CATINIC,CATFIM,DESCRICAO,DESCRABREV,Unnamed: 5,CID_GERAL
0,1,A00,B99,Capitulo I - Algumas Doenças infecciosas e par...,I. Algumas Doenças infecciosas e parasitárias,NaN,A
1,2,C00,D48,Capitulo II - Neoplasias [tumores],II. Neoplasias (tumores),NaN,C
2,3,D50,D89,Capitulo III - Doenças do sangue e dos órgãos...,III. Doenças sangue órgãos hemat e transt imun...,NaN,D
3,4,E00,E90,"Capitulo IV - Doenças endócrinas, nutricionais...",IV. Doenças endócrinas nutricionais e metaból...,NaN,E
4,5,F00,F99,Capitulo V - Transtornos mentais e comportamen...,V. Transtornos mentais e comportamentais,NaN,F
5,6,G00,G99,Capitulo VI - Doenças do sistema nervoso,VI. Doenças do sistema nervoso,NaN,G
6,7,H00,H59,Capitulo VII - Doenças do olho e anexos,VII. Doenças do olho e anexos,NaN,H
7,8,H60,H95,Capitulo VIII - Doenças do ouvido e da apófise...,VIII.Doenças do ouvido e da apófise mastóide,NaN,H
8,9,I00,I99,Capitulo IX - Doenças do aparelho circulatório,IX. Doenças do aparelho circulatório,NaN,I
9,10,J00,J99,Capitulo X - Doenças do aparelho respiratório,X. Doenças do aparelho respiratório,NaN,J
10,11,K00,K93,Capitulo XI - Doenças do aparelho digestivo,XI. Doenças do aparelho digestivo,NaN,K
11,12,L00,L99,Capitulo XII - Doenças da pele e do tecido sub...,XII. Doenças da pele e do tecido subcutâneo,NaN,L
12,13,M00,M99,Capitulo XIII - Doenças do sistema osteomuscul...,XIII.Doenças sist osteomuscular e tec conjuntivo,NaN,M
13,14,N00,N99,Capitulo XIV - Doenças do aparelho geniturinário,XIV. Doenças do aparelho geniturinário,NaN,N
14,15,O00,O99,"Capitulo XV - Gravidez, parto e puerpério",XV. Gravidez parto e puerpério,NaN,O
15,16,P00,P96,Capitulo XVI - Algumas afecções originadas no ...,XVI. Algumas afec originadas no período perinatal,NaN,P
16,17,Q00,Q99,"Capitulo XVII - Malformações congênitas, defor...",XVII.Malf cong deformid e anomalias cromossômicas,NaN,Q
17,18,R00,R99,"Capitulo XVIII - Sintomas, sinais e achados an...",XVIII.Sint sinais e achad anorm ex clín e laborat,NaN,R
18,19,S00,T98,"Capitulo XIX - Lesões, envenenamento e algumas...",XIX. Lesões enven e alg out conseq causas exte...,NaN,S
19,20,V01,Y98,Capitulo XX - Causas externas de morbidade e d...,XX. Causas externas de morbidade e mortalidade,NaN,V

In [21]:
df.drop(columns=['Unnamed: 5'], inplace=True)

In [27]:
dados_sus = pd.read_csv('/home/maiconkevyn/PycharmProjects/txt2sql_claude/data/dados_sus3.csv', sep=',')

dados_sus.head()

,DIAG_PRINC,MUNIC_RES,MUNIC_MOV,PROC_REA,IDADE,SEXO,CID_MORTE,MORTE,CNES,VAL_TOT,UTI_MES_TO,DT_INTER,DT_SAIDA,total_ocorrencias,UF_RESIDENCIA_PACIENTE,CIDADE_RESIDENCIA_PACIENTE,LATI_CIDADE_RES,LONG_CIDADE_RES
0,A46,430300,430300,303080078,67,3,0,0,2266474,292.62,0,20170803,20170808,24485,Rio Grande do Sul,Santa Maria,-29.686051,-53.806921
1,C168,430300,430300,304100021,60,1,0,0,2266474,797.11,0,20170803,20170805,24485,Rio Grande do Sul,Santa Maria,-29.686051,-53.806921
2,J128,430300,430300,303140151,76,3,0,1,2266474,4987.52,8,20170726,20170803,24485,Rio Grande do Sul,Santa Maria,-29.686051,-53.806921
3,I500,430300,430300,303060212,62,1,0,1,2266474,2702.50,4,20170802,20170805,24485,Rio Grande do Sul,Santa Maria,-29.686051,-53.806921
4,I158,430300,430300,303060107,29,3,0,0,2266474,1737.69,2,20170804,20170810,24485,Rio Grande do Sul,Santa Maria,-29.686051,-53.806921

In [28]:
casos_j = dados_sus[dados_sus['DIAG_PRINC'].str.startswith('O')]
casos_j.shape

(1401, 18)